#! /usr/bin/env bash

#BSUB -J peaks[1-13]
#BSUB -e peaks.%J.%I.err
#BSUB -o peaks.%J.%I.out
#BSUB -q short

<<DOC
call peaks using macs2.
DOC

set -o nounset -o pipefail -o errexit -x

source $CONFIG
sample=${SAMPLES[$(($LSB_JOBINDEX - 1))]}

results=$RESULT/$sample
peakresults="$results/peaks"

# yeast genome size
genomesize=12e6

# narrowPeak autosql
ucscdir=/vol1/software/modules-sw/ucsc/build/v286
asfile=$ucscdir/kent/src/hg/lib/encode/narrowPeak.as

# these params sometimes call huge stretches if signal is low. remove
# absurdly long peaks.
max_peaklength=5000

if [[ ! -f $peakresults ]]; then
    mkdir -p $peakresults
fi

# write files into the peaks directory
cd $peakresults

strands=("pos" "neg")
strand_flag=("-F 0x10", "-f 0x10")

# make pos and neg bam files
for strand_idx in ${!strands[@]}; do
    for align_mode in ${ALIGN_MODES[@]}; do

        strand=${strands[$strand_idx]}
        strand_flag=${strand_flag[$strand_idx]}

        bam=$RESULT/$sample/alignment/$sample.align.$align_mode.bam
        strandbam=$sample.align.$align_mode.strand.$strand.bam
        samtools view -hb $strand_flag $bam > $strandbam

        exp_name="$sample.align.$align_mode.strand.$strand"

        # this filename is generated by macs2
        narrowpeak="${exp_name}_peaks.narrowPeak"

        bigbed="${exp_name}.peaks.bb"

        macs2 callpeak -t $strandbam -n $exp_name \
            --keep-dup all --nomodel -s 25 --extsize 5 \
            --call-summits

        # sometimes the score exceeds the maximum (1000) defined by the
        # narrowPeak spec. Reformat the narrowPeak file to covert > 1000
        # to 1000
        narrowpeak_tmpfile="$narrowpeak.tmp"
        awk 'BEGIN {OFS="\t"} \
                   { if ($5 > 1000) $5 = 1000; print $0}' \
            < $narrowpeak \
            | awk -v maxlen=$max_peaklength '$3 - $2 < maxlen' \
            > $narrowpeak_tmpfile
        mv $narrowpeak_tmpfile $narrowpeak
        
        bedToBigBed -type=bed6+4 -as=$asfile \
            $narrowpeak $CHROM_SIZES $bigbed

    done
done

